// duanwu/html_react/src/components/SlideBackground.jsx
import React, { useRef, useState } from "react";

import "../assets/css/duanwu.css";
import "../assets/css/animate.min.css";

import corner from "../assets/images/corner.png"
import bamboo from "../assets/images/bamboo.png"
import moutain from "../assets/images/moutain.png"
import zongzi from "../assets/images/zongzi.png"
import wine from "../assets/images/wine.png"
import cloud from "../assets/images/cloud.png"

export default function SlideBackgound() {
  return (
    <>
      <img className="ani corner" src={corner} swiper-animate-effect="slideInDown"
        swiper-animate-duration="2s" swiper-animate-delay="0s" />
      <img className="ani bamboo" src={bamboo} swiper-animate-effect="slideInDown"
        swiper-animate-duration="2s" swiper-animate-delay="0s" />
      <img className="ani moutain" src={moutain} swiper-animate-effect="slideInUp"
        swiper-animate-duration="2s" swiper-animate-delay="0s" />
      <img className="ani zongzi" src={zongzi} swiper-animate-effect="fadeInUp"
        swiper-animate-duration="2s" swiper-animate-delay="0.5s" />
      <img className="ani wine" src={wine} swiper-animate-effect="fadeInUp"
        swiper-animate-duration="2s" swiper-animate-delay="0s" />
      <img className="ani cloud" src={cloud} swiper-animate-effect="fadeIn"
        swiper-animate-duration="2s" swiper-animate-delay="0s" />
    </>
  );
}

// duanwu/html_vue/src/components/SlideBackground.vue
<template>
    <div id="backgroundAnimation">
        <img class="ani corner" src="../assets/images/corner.png" swiper-animate-effect="slideInDown"
            swiper-animate-duration="2s" swiper-animate-delay="0s" />
        <img class="ani bamboo" src="../assets/images/bamboo.png" swiper-animate-effect="slideInDown"
            swiper-animate-duration="2s" swiper-animate-delay="0s" />
        <img class="ani moutain" src="../assets/images/moutain.png" swiper-animate-effect="slideInUp"
            swiper-animate-duration="2s" swiper-animate-delay="0s" />
        <img class="ani zongzi" src="../assets/images/zongzi.png" swiper-animate-effect="fadeInUp"
            swiper-animate-duration="2s" swiper-animate-delay="0.5s" />
        <img class="ani wine" src="../assets/images/wine.png" swiper-animate-effect="fadeInUp"
            swiper-animate-duration="2s" swiper-animate-delay="0s" />
        <img class="ani cloud" src="../assets/images/cloud.png" swiper-animate-effect="fadeIn"
            swiper-animate-duration="2s" swiper-animate-delay="0s" />
    </div>
</template>

<script>
import "../assets/css/duanwu.css";
import "../assets/css/animate.min.css";

export default {
    name: "SlideBackground"
}
</script>
